version: '3.8'

services:
  db:
    image: postgres:14.2-alpine3.15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  api:
    depends_on:
      - db
    build: ./api
    ports:
      - 5000:5000

volumes:
  db:
    driver: local
